import "../config/env.config.js";
import { connectDatabase } from "../utils/db.js";
import { Medicine } from "../models/Medicine.model.js";
import { HealthyProduct } from "../models/HealthyProduct.model.js";
import { HealthyCategory } from "../models/HealthyCategory.model.js";

export const ALL_MEDICINES_DATA = [
  // 1. Cold, Cough & Fever
  {
    name: "Crocin Advance 500mg Tablet",
    genericName: "Paracetamol 500mg",
    manufacturer: "GlaxoSmithKline",
    brand: "Crocin",
    description: "Fast acting pain relief and fever reducer with Optizorb technology. Begins releasing medicine in just 5 minutes.",
    category: "Cold, Cough & Fever",
    dosageForm: "Tablet",
    strength: "500mg",
    packaging: "Strip of 15 Tablets",
    price: 60,
    discountedPrice: 45,
    mrp: 60,
    sellingPrice: 45,
    discountPercentage: 25,
    stock: 500,
    requiresPrescription: false,
    rating: 4.6,
    totalRatings: 2456,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Paracetamol 650mg Tablet",
    genericName: "Paracetamol 650mg",
    manufacturer: "Micro Labs Ltd",
    brand: "Paracetamol",
    description: "High potency antipyretic and analgesic tablet for high fever, body ache and severe headache.",
    category: "Cold, Cough & Fever",
    dosageForm: "Tablet",
    strength: "650mg",
    packaging: "Strip of 15 Tablets",
    price: 15,
    discountedPrice: 12,
    mrp: 15,
    sellingPrice: 12,
    discountPercentage: 20,
    stock: 600,
    requiresPrescription: false,
    rating: 4.5,
    totalRatings: 1890,
    images: [
      "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Dolo 650 Tablet",
    genericName: "Paracetamol 650mg",
    manufacturer: "Micro Labs",
    brand: "Dolo",
    description: "India's most trusted paracetamol formulation for prompt relief from fever and mild-to-moderate pain.",
    category: "Cold, Cough & Fever",
    dosageForm: "Tablet",
    strength: "650mg",
    packaging: "Strip of 15 Tablets",
    price: 34,
    discountedPrice: 28,
    mrp: 34,
    sellingPrice: 28,
    discountPercentage: 18,
    stock: 450,
    requiresPrescription: false,
    rating: 4.8,
    totalRatings: 4200,
    images: [
      "https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Vicks Action 500 Advanced Tablet",
    genericName: "Paracetamol, Phenylephrine, Caffeine",
    manufacturer: "Procter & Gamble",
    brand: "Vicks",
    description: "Multi-symptom relief from cold, blocked nose, sinus headache, and fever.",
    category: "Cold, Cough & Fever",
    dosageForm: "Tablet",
    strength: "500mg",
    packaging: "Strip of 10 Tablets",
    price: 50,
    discountedPrice: 42,
    mrp: 50,
    sellingPrice: 42,
    discountPercentage: 16,
    stock: 350,
    requiresPrescription: false,
    rating: 4.4,
    totalRatings: 1240,
    images: [
      "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 2. Vitamins & Supplements
  {
    name: "Himalaya Liv.52 DS Tablet",
    genericName: "Herbal Liver Formulation",
    manufacturer: "The Himalaya Drug Company",
    brand: "Himalaya",
    description: "Double strength herbal hepatoprotective tablet supporting normal liver function and appetite restoration.",
    category: "Vitamins & Supplements",
    dosageForm: "Tablet",
    strength: "Double Strength",
    packaging: "Bottle of 60 Tablets",
    price: 260,
    discountedPrice: 210,
    mrp: 260,
    sellingPrice: 210,
    discountPercentage: 19,
    stock: 400,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 3120,
    images: [
      "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Zincovit Tablet",
    genericName: "Multivitamins with Zinc",
    manufacturer: "Apex Laboratories",
    brand: "Zincovit",
    description: "Comprehensive multivitamin, multimineral and grape seed extract tablet designed to build daily immunity.",
    category: "Vitamins & Supplements",
    dosageForm: "Tablet",
    strength: "Standard",
    packaging: "Strip of 15 Tablets",
    price: 130,
    discountedPrice: 110,
    mrp: 130,
    sellingPrice: 110,
    discountPercentage: 15,
    stock: 550,
    requiresPrescription: false,
    rating: 4.6,
    totalRatings: 2890,
    images: [
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Becosules Z Capsules",
    genericName: "Vitamin B-Complex with Zinc & Vitamin C",
    manufacturer: "Pfizer Ltd",
    brand: "Becosules",
    description: "Therapeutic vitamin B-complex with vitamin C and zinc for mouth ulcers, tissue repair, and vitality.",
    category: "Vitamins & Supplements",
    dosageForm: "Capsule",
    strength: "High Potency",
    packaging: "Strip of 20 Capsules",
    price: 55,
    discountedPrice: 45,
    mrp: 55,
    sellingPrice: 45,
    discountPercentage: 18,
    stock: 480,
    requiresPrescription: false,
    rating: 4.8,
    totalRatings: 3400,
    images: [
      "https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Shelcal 500mg Tablet",
    genericName: "Calcium 500mg + Vitamin D3 250 IU",
    manufacturer: "Torrent Pharmaceuticals",
    brand: "Shelcal",
    description: "Essential calcium and vitamin D3 supplement for bone strength, joint density, and fracture prevention.",
    category: "Vitamins & Supplements",
    dosageForm: "Tablet",
    strength: "500mg",
    packaging: "Strip of 15 Tablets",
    price: 135,
    discountedPrice: 115,
    mrp: 135,
    sellingPrice: 115,
    discountPercentage: 15,
    stock: 390,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 2150,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 3. Protein & Nutrition
  {
    name: "Electral ORS Orange Flavour",
    genericName: "Oral Rehydration Salts IP",
    manufacturer: "FDC Limited",
    brand: "Electral",
    description: "WHO-based oral rehydration salts to restore electrolyte balance and hydration during diarrhea and vomiting.",
    category: "Protein & Nutrition",
    dosageForm: "Powder",
    strength: "21.8g",
    packaging: "Pack of 21.8 gm",
    price: 30,
    discountedPrice: 26,
    mrp: 30,
    sellingPrice: 26,
    discountPercentage: 13,
    stock: 800,
    requiresPrescription: false,
    rating: 4.9,
    totalRatings: 4900,
    images: [
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Ensure Complete Nutrition Drink Vanilla",
    genericName: "Balanced Nutrition Drink",
    manufacturer: "Abbott Healthcare",
    brand: "Ensure",
    description: "Scientifically formulated complete, balanced nutrition with 32 essential nutrients for strength and energy.",
    category: "Protein & Nutrition",
    dosageForm: "Powder",
    strength: "400g",
    packaging: "Jar of 400 gm",
    price: 740,
    discountedPrice: 640,
    mrp: 740,
    sellingPrice: 640,
    discountPercentage: 14,
    stock: 180,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 1890,
    images: [
      "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 4. Pain Relief
  {
    name: "Omnigel Gel",
    genericName: "Diclofenac, Linseed Oil, Methyl Salicylate, Menthol",
    manufacturer: "Cipla Ltd",
    brand: "Omnigel",
    description: "Fast-absorbing topical pain relief gel for joint pain, backache, neck strain, and sports injuries.",
    category: "Pain Relief",
    dosageForm: "Gel",
    strength: "30g",
    packaging: "Tube of 30 gm",
    price: 90,
    discountedPrice: 75,
    mrp: 90,
    sellingPrice: 75,
    discountPercentage: 17,
    stock: 450,
    requiresPrescription: false,
    rating: 4.8,
    totalRatings: 3780,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Volini Pain Relief Spray 100g",
    genericName: "Diclofenac Diethylamine",
    manufacturer: "Sun Pharmaceutical",
    brand: "Volini",
    description: "Instant pain relief spray targeting deep muscle aches, sprains, and back pain.",
    category: "Pain Relief",
    dosageForm: "Spray",
    strength: "100g",
    packaging: "Spray Bottle of 100 gm",
    price: 260,
    discountedPrice: 220,
    mrp: 260,
    sellingPrice: 220,
    discountPercentage: 15,
    stock: 320,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 2900,
    images: [
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Dard Relief Gel",
    genericName: "Herbal Joint Pain Gel",
    manufacturer: "Healthys Pharma",
    brand: "Dard Relief",
    description: "Herbal cooling gel with Gandhpura, Nilgiri and Pudina for immediate muscle relaxation.",
    category: "Pain Relief",
    dosageForm: "Gel",
    strength: "30g",
    packaging: "Tube of 30 gm",
    price: 90,
    discountedPrice: 75,
    mrp: 90,
    sellingPrice: 75,
    discountPercentage: 17,
    stock: 250,
    requiresPrescription: false,
    rating: 4.5,
    totalRatings: 870,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 5. Ayurvedic Wellness
  {
    name: "Dabur Chyawanprash 1 kg",
    genericName: "Ayurvedic Immunity Formulation",
    manufacturer: "Dabur India Ltd",
    brand: "Dabur",
    description: "Time-tested Ayurvedic formulation with 40+ herbs, Amla, and natural antioxidants to protect against illnesses.",
    category: "Ayurvedic Wellness",
    dosageForm: "Paste",
    strength: "1kg",
    packaging: "Jar of 1 kg",
    price: 300,
    discountedPrice: 265,
    mrp: 300,
    sellingPrice: 265,
    discountPercentage: 12,
    stock: 300,
    requiresPrescription: false,
    rating: 4.9,
    totalRatings: 5600,
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Dabur 100% Pure Honey 500g",
    genericName: "Pure Natural Honey",
    manufacturer: "Dabur India Ltd",
    brand: "Dabur",
    description: "Pure and unadulterated natural honey containing natural antioxidants, minerals, and vitamins.",
    category: "Ayurvedic Wellness",
    dosageForm: "Liquid",
    strength: "500g",
    packaging: "Squeezy Bottle 500 gm",
    price: 240,
    discountedPrice: 199,
    mrp: 240,
    sellingPrice: 199,
    discountPercentage: 17,
    stock: 350,
    requiresPrescription: false,
    rating: 4.8,
    totalRatings: 3200,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 6. Diabetes
  {
    name: "Accu-Chek Active Test Strip",
    genericName: "Blood Glucose Test Strips",
    manufacturer: "Roche Diabetes Care",
    brand: "Accu-Chek",
    description: "Accurate blood glucose monitoring strips for self-testing with Accu-Chek Active glucometer.",
    category: "Diabetes",
    dosageForm: "Strips",
    strength: "50 Strips",
    packaging: "Pack of 50 Strips",
    price: 950,
    discountedPrice: 799,
    mrp: 950,
    sellingPrice: 799,
    discountPercentage: 16,
    stock: 220,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 1840,
    images: [
      "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 7. Baby Care
  {
    name: "Sebamed Baby Cleansing Bar 100g",
    genericName: "Soap-Free Baby Cleansing Bar",
    manufacturer: "Sebapharma Germany",
    brand: "Sebamed",
    description: "100% soap-free and alkali-free gentle cleansing bar with pH 5.5 for newborn sensitive skin.",
    category: "Baby Care",
    dosageForm: "Bar",
    strength: "100g",
    packaging: "Bar of 100 gm",
    price: 280,
    discountedPrice: 240,
    mrp: 280,
    sellingPrice: 240,
    discountPercentage: 14,
    stock: 190,
    requiresPrescription: false,
    rating: 4.9,
    totalRatings: 2100,
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 8. Oral Care
  {
    name: "Sensodyne Fresh Gel Toothpaste 150g",
    genericName: "Potassium Nitrate Toothpaste",
    manufacturer: "GSK Consumer Healthcare",
    brand: "Sensodyne",
    description: "Clinically proven daily sensitivity relief with long-lasting freshness and cavity protection.",
    category: "Oral Care",
    dosageForm: "Paste",
    strength: "150g",
    packaging: "Tube of 150 gm",
    price: 260,
    discountedPrice: 220,
    mrp: 260,
    sellingPrice: 220,
    discountPercentage: 15,
    stock: 280,
    requiresPrescription: false,
    rating: 4.8,
    totalRatings: 3100,
    images: [
      "https://images.unsplash.com/photo-1559591937-e10323971b3e?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 9. Personal Care
  {
    name: "Dettol Antiseptic Liquid 550ml",
    genericName: "Chloroxylenol Antiseptic",
    manufacturer: "Reckitt Benckiser",
    brand: "Dettol",
    description: "Trusted first-aid antiseptic liquid for cuts, wounds, bites, hygiene, and laundry disinfection.",
    category: "Personal Care",
    dosageForm: "Liquid",
    strength: "550ml",
    packaging: "Bottle of 550 ml",
    price: 240,
    discountedPrice: 205,
    mrp: 240,
    sellingPrice: 205,
    discountPercentage: 15,
    stock: 320,
    requiresPrescription: false,
    rating: 4.9,
    totalRatings: 4100,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 10. Sexual Wellness
  {
    name: "Durex Invisible Extra Thin Condoms",
    genericName: "Natural Rubber Latex Condoms",
    manufacturer: "Reckitt Benckiser",
    brand: "Durex",
    description: "Ultra-thin lubricated condoms designed for maximum sensitivity and natural feeling.",
    category: "Sexual Wellness",
    dosageForm: "Pack",
    strength: "10 Pack",
    packaging: "Pack of 10",
    price: 275,
    discountedPrice: 230,
    mrp: 275,
    sellingPrice: 230,
    discountPercentage: 16,
    stock: 240,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 2500,
    images: [
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 11. Hair Care
  {
    name: "Indulekha Bringha Ayurvedic Hair Oil 100ml",
    genericName: "Ayurvedic Hair Growth Oil",
    manufacturer: "Hindustan Unilever",
    brand: "Indulekha",
    description: "100% Ayurvedic hair oil with selfie applicator. Clinically proven to grow new hair in 4 months.",
    category: "Hair Care",
    dosageForm: "Oil",
    strength: "100ml",
    packaging: "Bottle of 100 ml",
    price: 440,
    discountedPrice: 380,
    mrp: 440,
    sellingPrice: 380,
    discountPercentage: 14,
    stock: 260,
    requiresPrescription: false,
    rating: 4.7,
    totalRatings: 3200,
    images: [
      "https://images.unsplash.com/photo-1608248597359-2ff9e3b97b09?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 12. Skin Care
  {
    name: "Betnovate-C Skin Cream 30g",
    genericName: "Betamethasone & Clioquinol",
    manufacturer: "GlaxoSmithKline",
    brand: "Betnovate",
    description: "Topical antifungal and corticosteroid cream for inflammatory and fungal skin disorders.",
    category: "Skin Care",
    dosageForm: "Cream",
    strength: "30g",
    packaging: "Tube of 30 gm",
    price: 78,
    discountedPrice: 65,
    mrp: 78,
    sellingPrice: 65,
    discountPercentage: 17,
    stock: 310,
    requiresPrescription: true,
    rating: 4.6,
    totalRatings: 1750,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=80",
    ],
  },

  // 13. Gut Care
  {
    name: "Digene Acidity & Gas Relief Gel Mint 200ml",
    genericName: "Magnesium Hydroxide, Aluminium Hydroxide, Simethicone",
    manufacturer: "Abbott Healthcare",
    brand: "Digene",
    description: "Fast-acting cooling antacid gel providing prompt relief from heartburn, indigestion, and gas.",
    category: "Gut Care",
    dosageForm: "Liquid",
    strength: "200ml",
    packaging: "Bottle of 200 ml",
    price: 170,
    discountedPrice: 145,
    mrp: 170,
    sellingPrice: 145,
    discountPercentage: 15,
    stock: 290,
    requiresPrescription: false,
    rating: 4.8,
    totalRatings: 2800,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },
];

// Healthy Store Products (Image 3)
export const HEALTHY_PRODUCTS_DATA = [
  {
    name: "Neem Tablets",
    category: "Ayurveda",
    brand: "Healthys",
    description: "Pure organic Neem leaf extract tablets for blood purification, radiant skin, and natural immunity defense.",
    price: 249,
    discountedPrice: 199,
    stock: 200,
    packSize: "Bottle of 60 Tablets",
    rating: 4.8,
    benefits: ["Purifies blood naturally", "Promotes healthy, glowing skin", "Strong antibacterial defense"],
    ingredients: ["Pure Neem Extract 500mg"],
    howToUse: "Take 1-2 tablets daily after meals with water.",
    isBestseller: true,
    subtitle: "Immunity & Skin Care",
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Ashwagandha Capsules",
    category: "Ayurveda",
    brand: "Healthys",
    description: "KSM-66 standardized full spectrum Ashwagandha root extract for stress reduction, stamina, and restful sleep.",
    price: 299,
    discountedPrice: 249,
    stock: 220,
    packSize: "Bottle of 60 Veg Capsules",
    rating: 4.9,
    benefits: ["Relieves everyday anxiety & stress", "Enhances muscle recovery & stamina", "Promotes natural circadian sleep"],
    ingredients: ["Organic KSM-66 Ashwagandha 500mg"],
    howToUse: "Take 1 capsule twice daily with warm milk or water.",
    isBestseller: false,
    subtitle: "Stress Relief & Strength",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Triphala Powder",
    category: "Ayurveda",
    brand: "Healthys",
    description: "Traditional blend of Amla, Haritaki and Bibhitaki for natural digestive cleansing and metabolic health.",
    price: 189,
    discountedPrice: 149,
    stock: 180,
    packSize: "Jar of 100 gm",
    rating: 4.7,
    benefits: ["Gentle overnight colon cleanse", "Supports healthy digestion", "Rich in natural Vitamin C"],
    ingredients: ["Amla", "Haritaki", "Bibhitaki"],
    howToUse: "Mix 1 teaspoon with warm water before bed.",
    isBestseller: true,
    subtitle: "Digestive Health",
    images: [
      "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Tulsi Drops",
    category: "Ayurveda",
    brand: "Healthys",
    description: "Pure extract of 5 sacred Tulsi varieties (Panch Tulsi) for respiratory health, cold protection, and cough relief.",
    price: 219,
    discountedPrice: 179,
    stock: 250,
    packSize: "Bottle of 30 ml",
    rating: 4.8,
    benefits: ["Relieves sore throat & chest congestion", "Strong respiratory immunity", "100% natural antioxidant"],
    ingredients: ["Shyam Tulsi", "Ram Tulsi", "Shukla Tulsi", "Van Tulsi", "Nimbu Tulsi"],
    howToUse: "Add 2-3 drops in a glass of warm water or tea, twice daily.",
    isBestseller: false,
    subtitle: "Respiratory Health",
    images: [
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Healthys Chyawanprash",
    category: "Ayurveda",
    brand: "Healthys",
    description: "Pure Amla-based traditional Ayurvedic rasayana with gold and silver bhasma for all-season immunity.",
    price: 360,
    discountedPrice: 299,
    stock: 150,
    packSize: "Jar of 500 gm",
    rating: 4.8,
    benefits: ["Boosts antibodies & vitality", "Enhances stamina", "Safe for all age groups"],
    ingredients: ["Fresh Amla", "Ghee", "Honey", "45 Ayurvedic Herbs"],
    howToUse: "1 tablespoon twice daily with warm milk.",
    isBestseller: false,
    subtitle: "Daily Vitality & Immunity",
    images: [
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80",
    ],
  },
  {
    name: "Brahmi Tablets",
    category: "Ayurveda",
    brand: "Healthys",
    description: "Centella Asiatica (Gotu Kola) & Bacopa Monnieri extract to enhance cognitive focus, memory, and calmness.",
    price: 230,
    discountedPrice: 189,
    stock: 190,
    packSize: "Bottle of 60 Tablets",
    rating: 4.7,
    benefits: ["Sharpens mental focus", "Reduces cognitive fatigue", "Calms anxious mind"],
    ingredients: ["Pure Brahmi Extract 500mg"],
    howToUse: "Take 1 tablet twice daily after meals.",
    isBestseller: false,
    subtitle: "Memory & Focus",
    images: [
      "https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=500&auto=format&fit=crop&q=80",
    ],
  },
  // Nutrition
  {
    name: "Plant Protein Powder 1kg Chocolate",
    category: "Nutrition",
    brand: "Healthys",
    description: "25g clean organic pea and brown rice protein per serving with zero added sugar and natural cocoa.",
    price: 2499,
    discountedPrice: 1899,
    stock: 100,
    packSize: "1 kg Tub",
    rating: 4.8,
    benefits: ["25g protein per scoop", "Zero dairy, zero bloating", "Added digestive enzymes"],
    ingredients: ["Pea Protein Isolate", "Brown Rice Protein", "Cocoa Powder"],
    howToUse: "Mix 1 scoop with 250ml water or almond milk.",
    isBestseller: true,
    subtitle: "Clean Protein Shake",
    images: [
      "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500&auto=format&fit=crop&q=80",
    ],
  },
  // Natural Care
  {
    name: "Organic Aloe Vera Gel 200ml",
    category: "Natural Care",
    brand: "Healthys",
    description: "99% pure cold-pressed organic aloe vera gel for deep hydration, soothing sunburn, and acne relief.",
    price: 260,
    discountedPrice: 199,
    stock: 140,
    packSize: "Tub of 200 ml",
    rating: 4.9,
    benefits: ["Instantly cools and soothes skin", "Non-sticky daily hydration", "100% paraben & mineral oil free"],
    ingredients: ["Organic Aloe Barbadensis Leaf Juice 99%"],
    howToUse: "Apply generously on clean face and neck daily.",
    isBestseller: true,
    subtitle: "Pure & Safe Skin Care",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=80",
    ],
  },
];

async function seedAll() {
  console.log("Connecting to database...");
  await connectDatabase();

  console.log("\n1. Seeding Medicines...");
  // Clear placeholder medicines or update with real items
  for (const med of ALL_MEDICINES_DATA) {
    await Medicine.findOneAndUpdate(
      { name: med.name },
      { ...med, isActive: true },
      { upsert: true, new: true }
    );
  }
  const medCount = await Medicine.countDocuments({ isActive: true });
  console.log(`✅ Active Medicines in database: ${medCount}`);

  console.log("\n2. Linking Frequently Bought Together medicines...");
  const crocin = await Medicine.findOne({ name: "Crocin Advance 500mg Tablet" });
  const electral = await Medicine.findOne({ name: "Electral ORS Orange Flavour" });
  const paracetamol = await Medicine.findOne({ name: "Paracetamol 650mg Tablet" });
  const dardRelief = await Medicine.findOne({ name: "Dard Relief Gel" });

  if (crocin && electral && paracetamol && dardRelief) {
    crocin.frequentlyBoughtTogether = [electral._id, paracetamol._id, dardRelief._id];
    await crocin.save();
    console.log("✅ Frequently Bought Together linked for Crocin Advance!");
  }

  console.log("\n3. Seeding Healthy Store Products...");
  for (const prod of HEALTHY_PRODUCTS_DATA) {
    await HealthyProduct.findOneAndUpdate(
      { name: prod.name },
      { ...prod, isActive: true },
      { upsert: true, new: true }
    );
  }
  const healthyCount = await HealthyProduct.countDocuments({ isActive: true });
  console.log(`✅ Active Healthy Products in database: ${healthyCount}`);

  console.log("\n🎉 ALL REAL MEDICINES AND HEALTHY PRODUCTS SEEDED SUCCESSFULLY!");
  process.exit(0);
}

seedAll().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
